# Generated by Django 2.0.6 on 2018-06-05 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='mapping',
            index=models.Index(fields=['z', 'x', 'y'], name='mapping_map_z_062aef_idx'),
        ),
    ]
