# Generated by Django 2.0.6 on 2018-12-26 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0002_auto_20180605_1413'),
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('z', models.IntegerField()),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('active', models.BooleanField(default=False)),
                ('url', models.URLField()),
                ('name', models.TextField()),
            ],
        ),
    ]
