# Generated by Django 2.0.6 on 2018-12-26 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0005_auto_20181226_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='url_postfix',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddIndex(
            model_name='server',
            index=models.Index(fields=['z', 'x', 'y'], name='mapping_ser_z_5c1e4a_idx'),
        ),
        migrations.AddIndex(
            model_name='server',
            index=models.Index(fields=['active'], name='mapping_ser_active_87086c_idx'),
        ),
    ]
