# Generated by Django 3.0.5 on 2020-05-07 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0006_auto_20181226_1555'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mapping',
        ),
    ]
