# Generated by Django 3.0.5 on 2020-05-08 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service_accounts', '0001_initial'),
        ('mapping', '0007_delete_mapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='managed_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='service_accounts.ServiceAccount'),
        ),
    ]
