# Generated by Django 3.0.5 on 2020-05-24 10:02

from django.db import migrations, models
import tileservermapping.osm_data.models


class Migration(migrations.Migration):

    replaces = [('osm_data', '0001_initial'), ('osm_data', '0002_auto_20200524_0924'), ('osm_data', '0003_auto_20200524_0930'), ('osm_data', '0004_auto_20200524_0937')]

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlanetDump',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField(help_text='Slippy map coordinate X')),
                ('y', models.IntegerField(help_text='Slippy map coordinate Y')),
                ('z', models.IntegerField(help_text='Slippy map coordinate Z (zoom)')),
                ('file', models.FileField(upload_to=tileservermapping.osm_data.models.generate_file_name)),
            ],
            options={
                'unique_together': set(),
            },
        ),
        migrations.AddConstraint(
            model_name='planetdump',
            constraint=models.UniqueConstraint(fields=('x', 'y', 'z'), name='unique_coordinates'),
        ),
    ]
