# Generated by Django 2.2.1 on 2020-02-09 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mapping', '0006_auto_20181226_1555'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlowTiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('z', models.IntegerField()),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('count', models.IntegerField(default=1)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mapping.Server')),
            ],
            options={
                'unique_together': {('z', 'x', 'y')},
            },
        ),
    ]
